# Generated by Django 4.2.7 on 2023-11-28 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_lessonhistory_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonhistory',
            name='starting_point',
        ),
    ]
